---
title: "Validator Economics: Proposer selection - random bytes"
author:
- name: Sandra Johnson
  url: https://twitter.com/sandJohnson
  affiliation: Consensys Software Inc (Research Group)
date: "`r Sys.Date()`"
description: 
  Visualisation of the random bytes generated by the spec for validators.
editor_options: 
  markdown: 
    wrap: 72
---

```{r message=FALSE}
#library(data.table)
library(ggplot2)
library(knitr)
library(lubridate)
library(rmarkdown)
library(skimr)
library(tidyverse)

options(digits=10)
options(scipen = 999) 

# See knit options in https://www.r-bloggers.com/2021/03/default-knitr-options-and-hooks/ 
knitr::opts_chunk$set(dpi = if (knitr::is_latex_output()) 72 else 300,
                      echo=FALSE)
```

## Blog post - graph of 716,800 randomly drawn values from U(0,255)
- After the values have been drawn, we need to ensure that they are all *integer values*. We cannot have values greater than 255, so we use the floor function to round down to the nearest integer value.
```{r cache=TRUE}
set.seed(1)

random_byte_values <- runif(716800,0,255)
## ----------------------------------------------
r_int <- floor(random_byte_values)
x <- seq(0,255,1)
r <- data.frame(r_int)

df <- r %>%
  group_by(r_int) %>%
  summarise(y = n()) %>%
  arrange(r_int)

df <- df %>%
  mutate(prob = y/sum(y))

# Plot the proportion of validators receiving particular random bytes (integers)
# Note that there is a small range of values. When we specify ylim(0,0.005) we get a better idea of how close these values are, i.e. all scattered around 0.004.
# ------------------------------------------------------------------------------------------------------
ggplot(data=df, aes(x=r_int,y=prob))  +
  xlab("random_byte values generated from U(0,255)") +
  ylab("proportion of validator set") +
  #ylim(0,0.005) +
  geom_point()  
#ggsave("/Users/sandra/data/validator-economics/plots/random-values-generated.png") 

```
```{r}
# Plot the random integers generated by the spec & overlay a uniform distribution
# -------------------------------------------------------------------------------
transparentlightblue <- rgb(173,216,230,max = 255, alpha = 80) # using transparent colour for uniform dist

ggplot(r, aes(x=r_int)) + geom_histogram(bins = 255, aes(y=..density..)) +
   stat_function(fun = dunif, args = list(min = 0, max = 255), geom = "area", 
                  fill = transparentlightblue) + 
    stat_function(fun = dunif, args = list(min = 0, max = 255)) +
  xlab("random bytes generated in 'compute_proposer_index'") +
  ylab("proportion of validators")

#ggsave("/Users/sandra/data/validator-economics/plots/random-integers-and-uniform.png")

```



# Blog post - Q-Q plot of random byte values
```{r}
ggplot() +
  geom_qq(data=r, aes(sample=r_int), colour = "turquoise", distribution=qunif) +
  geom_abline(slope=255,intercept=0) +
  coord_flip()

#ggsave("/Users/sandra/data/validator-economics/plots/random-integers-QQ.png")

```